### ISSUE TITLE
MidDeletion lead to genotypes with a blank allele

### ISSUE THREAD

**Issue by arahuja** [hammerlab/guacamole#275]
There are two problems with deletions that overlap with SNV, as in the image below

![image](https://cloud.githubusercontent.com/assets/455755/5849674/9c8f14ea-a1b6-11e4-9fc9-47d05a17c8f0.png)

The pileup preceding the SNV will evaluate the deletion and possibly call a deletion, however this leads to two problems in the next position
1. the next position contains both MidDeletion and Mismatch elements.  MidDeletion elements do not define reference or alternate alleles so both are empty (but equal) but labeled as "reference"
2. whether or not we call deletion before should affect whether or not we call the SNV at the next position

**Comment by ryan-williams** [comment]
yea, interesting, can we start by constructing a test case that exercises this problem? A het 1bp deletion with a het SNV right after it (one chromosome is missing the base, the other has a non-ref base)?

If that sounds right to you I'll add it in a branch and then we can work on ways to make the test case pass.

I'm guessing we'll need to emit the reference base on each `MidDeletion` in order to properly know what's going on at the half-deleted-half-alt pileup?

**Comment by arahuja** [comment]
Yea that sounds good, if you want this exact case it is in the tumor bam of synthetic 3 set of the SMC challenge - chromosome 1:1017028
