### ISSUE TITLE
Use git lfs for large files

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/guacamole#473]
@arahuja made an attempt in #467 but couldn't get Travis to work. It would be good to get our BAMs out of the repo.

**Comment by arahuja** [comment]
Closed by #477, but I think we are going to revert this due to space and bandwith limits?

I think the big question is whether we want the test datafiles to be versioned at all? If not, we can just throw up somewhere else (google bucket) and have a script to download them, similar to the `git lfs pull` command. Otherwise, we can go back to having them in the repo.

**Comment by timodonnell** [comment]
I'd be fine keeping them versioned and going back to what we had before. If at some point we start having non-developer users (for whom downloading the test data is an annoyance when all they want to do is run guacamole) then we can revisit

**Comment by arahuja** [comment]
Closed by #477 and then reverted by #481
